// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCXvgEhelIKP_pYidy81-y4G87FpUbol0',
    appId: '1:894652240333:web:01f63b0a3fb6f8b4c13484',
    messagingSenderId: '894652240333',
    projectId: 'tarim-ai',
    authDomain: 'tarim-ai.firebaseapp.com',
    storageBucket: 'tarim-ai.appspot.com',
    measurementId: 'G-W079B56SBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWHDBrPesRNxTXc7Y5bhtPqlljrF6dGl4',
    appId: '1:894652240333:android:a5c22ff3ec8b270bc13484',
    messagingSenderId: '894652240333',
    projectId: 'tarim-ai',
    storageBucket: 'tarim-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHXRoHB11SQWaESOoi0B1wW5g_w3Q9tj4',
    appId: '1:894652240333:ios:70a93d204478a97dc13484',
    messagingSenderId: '894652240333',
    projectId: 'tarim-ai',
    storageBucket: 'tarim-ai.appspot.com',
    iosBundleId: 'com.example.tarimAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHXRoHB11SQWaESOoi0B1wW5g_w3Q9tj4',
    appId: '1:894652240333:ios:78eff636e56dcd58c13484',
    messagingSenderId: '894652240333',
    projectId: 'tarim-ai',
    storageBucket: 'tarim-ai.appspot.com',
    iosBundleId: 'com.example.tarimAi.RunnerTests',
  );
}
